trigger:
- master

variables:
  NodeVersion: '10.x'

jobs:
  - job: 'Build'

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(NodeVersion)'
        displayName: 'Install Node.js $(NodeVersion)'

      - task: Npm@1
        displayName: 'npm install'
        inputs:
          verbose: false

      - script: 'gulp build'
        displayName: 'gulp build'

      - script: 'gulp test'
        displayName: 'gulp test'

      - task: EsrpCodeSigning@1
        inputs:
          ConnectedServiceName: 'Swaggger Tools ESRP connection'
          FolderPath: 'src/dotnet/AutoRest/bin/netcoreapp2.0'
          Pattern: '*.dll,*.exe'
          signConfigType: 'inlineSignParams'
          inlineOperation: |
            [
                {
                    "KeyCode": "CP-230012",
                    "OperationSetCode": "SigntoolSign",
                    "parameters": [
                        {
                            "parameterName": "OpusName",
                            "parameterValue": "Microsoft"
                        },
                        {
                            "parameterName": "OpusInfo",
                            "parameterValue": "http://www.microsoft.com"
                        },
                        {
                            "parameterName": "PageHash",
                            "parameterValue": "/NPH"
                        },
                        {
                            "parameterName": "FileDigest",
                            "parameterValue": "/fd sha256"
                        },
                        {
                            "parameterName": "TimeStamp",
                            "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                        }
                    ],
                    "ToolName": "signtool.exe",
                    "ToolVersion": "6.2.9304.0"
                }
            ]
          SessionTimeout: '60'
          MaxConcurrency: '50'
          MaxRetryAttempts: '5'

      - script: 'gulp pack'
        displayName: 'gulp pack'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)/dist

  - job: Windows
    displayName: credentialScan
    pool:
      vmImage: "windows-2019"

    steps:
      - task: CredScan@2
        inputs:
          toolMajorVersion: 'V2'

      - task: PostAnalysis@1
        inputs:
          AllTools: false
          APIScan: false
          BinSkim: false
          CodesignValidation: false
          CredScan: true
          FortifySCA: false
          FxCop: false
          ModernCop: false
          PoliCheck: false
          RoslynAnalyzers: false
          SDLNativeRules: false
          Semmle: false
          TSLint: false
          ToolLogsNotFoundAction: 'Standard'

