language: node
dist: trusty
language: node_js
git:
  submodules: false
node_js:
  - "10.20.1"
install:
  # dotnet 2.0 prereq
  - sudo apt-get install libunwind8
  # node packages
  - npm install
script:
  - gulp