parameters:
- name: 'NodeVersion'
  default: '12.x'
  type: string

steps:
  - task: AzureCLI@2
    displayName: Test Azure CLI
    inputs:
      azureSubscription: Azure
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az account show
  - task: AzureCLI@2
    displayName: Test Azure CLI2
    inputs:
      azureSubscription: Azure
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az get-access-token
  - task: NodeTool@0
    inputs:
      versionSpec: '${{ parameters.NodeVersion }}'
    displayName: 'Install Node.js ${{ parameters.NodeVersion }}'

  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'rush install'

  - script: 'node common/scripts/install-run-rush.js rebuild --verbose'
    displayName: 'rush build'
