variables:
  NODE_OPTIONS: '--max-old-space-size=8192'
  NodeVersion: '12.x'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NodeVersion)'
    displayName: 'Install Node.js $(NodeVersion)'

  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'rush install'

  - script: 'node common/scripts/install-run-rush.js rebuild --verbose'
    displayName: 'rush build'