pool:
  vmImage: "Ubuntu 18.04"

trigger:
  - master

pr:
  branches:
    include:
      - "*"
variables:
  NODE_OPTIONS: '--max-old-space-size=8192'
  
steps:
  - script: git submodule update --init
    displayName: Init submodule
    condition: always()

  - task: Npm@1
    displayName: "npm install"
    inputs:
      verbose: false

  - script: 'gulp build'
    displayName: 'gulp build'

  - task: Npm@1
    displayName: "npm run regression-test"
    inputs:
      command: custom
      verbose: false
      customCommand: run regression-test

  # this command will return non zero if git repo has changes ie if the snapshots have been updated
  - script: echo "If this step fails, go to the published artifacts apply the patch provided to your local git repo using `git apply <file>`" && git diff-index --quiet HEAD --
    displayName: Fail test if snapshots have been updated
    condition: always()

  - script: git diff > $(Build.ArtifactStagingDirectory)/snapshot.patch
    displayName: Publish jest update snapshot patch
    condition: always()

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/snapshot.patch
      artifactName: "snapshot-patch"
