variables:
  NODE_OPTIONS: '--max-old-space-size=8192'

jobs:
  - job: 'Release_Build'
    pool:
      name: 'azsdk-pool-mms-ubuntu-2204-general'
      vmImage: 'ubuntu-22.04'

    steps:
      - template: common-build.yml

      - script: 'node common/scripts/install-run-rush.js pack'
        displayName: 'rush pack'

      - task: CopyFiles@2
        displayName: 'Copy Files to: dist'
        inputs:
          Contents: |
            packages/**/*.tgz
          TargetFolder: '$(Build.SourcesDirectory)/dist'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)/dist

