extends:
  template: /azure-pipelines/1es-redirect.yml
  parameters:
    stages:
    - stage: Prod_Release
      displayName: Prod Release

      variables:
        - template: /azure-pipelines/image.yml
        - name: NODE_OPTIONS
          value: --max-old-space-size=8192

      jobs:
      - job: 'Release_Build'
        displayName: Prod Release Build
        pool:
          name: $(LINUXNEXTPOOL)
          image: $(LINUXNEXTVMIMAGE)
          os: linux

        steps:
          - template: common-build.yml

          - script: 'node common/scripts/install-run-rush.js pack'
            displayName: 'rush pack'

          - task: CopyFiles@2
            displayName: 'Copy Files to: dist'
            inputs:
              Contents: |
                packages/**/*.tgz
              TargetFolder: '$(Build.SourcesDirectory)/dist'

          - template: /azure-pipelines/publish-1es-artifact.yml
            parameters:
              ArtifactName: drop
              ArtifactPath: $(Build.SourcesDirectory)/dist
