parameters:
  - name: Version
    type: string
    default: 'staging'
    values:
      - 'beta'
      - 'latest'

stages:
  - stage: Release
    displayName: Release ${{ parameters.Version }}
    dependsOn: Build

    jobs:
      - deployment: Publish
        environment: 'package-publish'
        pool:
          name: azsdk-pool-mms-ubuntu-2004-general
          image: azsdk-pool-mms-ubuntu-2004-1espt
          os: linux

        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
                submodules: false

              - download: current
                artifact: drop
                timeoutInMinutes: 5

              - pwsh: |
                  Write-Host "Will deploy with tag of $(Tag)"
                  Get-ChildItem "$(Pipeline.Workspace)/drop" -Recurse -Force `
                    | Where-Object { $_.Name -like "*.tgz" } `
                    | Copy-Item -Destination "$(Build.ArtifactStagingDirectory)"

                  Get-ChildItem "$(Build.ArtifactStagingDirectory)" -Recurse -Force | % { Write-Host $_.FullName }
                displayName: Move artifact to $(Build.ArtifactStagingDirectory)
